apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana-local
  nfs:
    server: 192.168.1.150    # Master node (NFS server)
    path: /exports/grafana-data
