apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: fullstack
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
      - name: backend
        image: ghcr.io/abdo-salem9982/devops-lab/backend:98b611ac0c52b5d3a494fb9d19caa144abcf97c8
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-configmap
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
